site_name: Xis LoRa documentation
nav:
    - 'Overview': index.md
    - 'Tutorials': Tutorials.md
    - 'Implementations': 
      - 'Connector': Connector.md
      - 'Server': Server.md
      - 'Join Server': Join.md
      - 'Controller': Controller.md
      - 'Motes Emulator': Motes.md
    - 'Source&Contact': Source&Contact.md
theme: readthedocs