site_name: Xis LoRa documentation
nav:
    - Home: 
      - Home: index.md
    - Network Server: 
      - Overview: Server/index.md
      - HTTP APIs: Server/http.md
    - Network Controller:
      - MAC Command Organizer: Controller/index.md
theme: readthedocs