site_name: Xis LoRa documentation
nav:
    - 'Overview': index.md
    - 'Tutorials': Tutorials.md
    - 'Implementations': 
      - 'Connector': Implementations/Connector.md
      - 'Server': Implementations/Server.md
      - 'Join Server': Implementations/Join.md
      - 'Controller': Implementations/Controller.md
      - 'Motes Emulator': Implementations/Motes.md
    - 'Source&Contact': Source&Contact.md
theme: readthedocs