site_name: Xis LoRa documentation
pages:
    - Overview: index.md
    - Tutorials: 
      - Installation: Tutorials/Installation.md
      - Configuration: Tutorials/Configuration.md
      - Installation of LoRa Web Server: Tutorials/Installation of LoRa Web Server.md
      - Usage: Tutorials/Usage.md
      - Application Integration: Tutorials/Application Integration.md
    - Implementations: 
      - Connector: Implementations/Connector.md
      - Server: Implementations/Server.md
      - Join Server: Implementations/Join.md
      - Controller: Implementations/Controller.md
      - Motes Emulator: Implementations/Motes.md
    - Source&Contact: Source&Contact.md
theme: readthedocs
copyright: Copyright &copy; 2018 <a href="https://www.xisiot.com/" target="_blank">Xisiot</a>, Maintained by the Xisiot Team.